# Generated by Django 5.2.7 on 2025-11-15 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_clientprofile_doctorprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DOCTOR', 'Doctor'), ('HOSPITAL', 'Hospital')], default='CLIENT', max_length=50),
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/hospitals/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
